# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.9"
  config.vm.network "private_network", ip: "192.168.33.111"
  config.vm.synced_folder "./ansible", "/ansible", create: true, mount_options: ['dmode=777','fmode=777']
  config.ssh.insert_key = false
  
  config.vm.provision "shell", inline: <<-SHELL
     yum -y install epel-release
     yum -y install ansible
     
     cd /ansible
     ansible-playbook -i hosts playbook.yml
  SHELL
end
