# https://docs.ansible.com/ansible/2.9_ja/modules/postgresql_user_module.html
- name: add user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{user_name}}"
    password: "password"

# https://docs.ansible.com/ansible/2.9_ja/modules/postgresql_db_module.html#postgresql-db-module
- name: create db
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{db_name}}"
    owner: "{{user_name}}"
    encoding: "UTF-8"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"
    template: "template0"